env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "0.0.0.0:8082"
  server_port: "8082"
  timeout: 4s
  idle_timeout: 60s
db:
  max_pool_size: 20
log:
  level: 'debug'
kafka:
  brokers: ["localhost:9092"]
  topic: "your_topic_name"
redis:
  address: "localhost:6379"




